export default function Head() {
    return (
      <>
        <title>ServiceDotBt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Next.js, React, Web Development, Frontend" />
        <meta name="author" content="Your Name or Team" />
        <link rel="icon" href="/favicon.ico" />
      </>
    );
  }
  